LW-969 Initial infrastructure
ndlib/contentful_maps_blueprints pull request #1
Opened 2020-10-15 15:05 UTC by mlkirkpatrick

Just a single lambda with an API gateway, and a CodePipeline.

2020-10-15 16:08 UTC, rdoughty approved these changes

2020-10-15 18:28 UTC, danthewolfe approved these changes

2020-10-16 15:40 UTC, jgondron requested changes

2020-10-16 15:40 UTC, jgondron commented on lib/contentful-maps-pipeline-stack.ts
> +      actions: [deployToTestAction, manualApprovalAction],
Please add some form of automated tests such as smoke tests at a minimum

2020-10-16 20:54 UTC, mlkirkpatrick commented on lib/contentful-maps-pipeline-stack.ts
> +      actions: [deployToTestAction, manualApprovalAction],
Added test. Had to add a parameter (and appropriate permissions) to pass the api url down.

2020-10-22 14:17 UTC, jgondron approved these changes

2020-10-22 14:20 UTC, merged